/* 
This file is auto generated by pgx.

The ordering of items is not stable, it is driven by a dependency graph.
*/

-- extension/src/lib.rs:16
-- table_builder::hello_table_builder
CREATE OR REPLACE FUNCTION "hello_table_builder"() RETURNS text /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'hello_table_builder_wrapper';

-- extension/src/lib.rs:7
CREATE TABLE TestTable (
    foo integer NOT NULL,
    bar bigint NOT NULL,
    baz text NOT NULL,
    avg double precision NOT NULL
);

