/* 
This file is auto generated by pgx.

The ordering of items is not stable, it is driven by a dependency graph.
*/

-- extension/src/lib.rs:12
CREATE TABLE ExampleTable (
    foo integer NOT NULL,
    bar bigint NOT NULL,
    baz text NOT NULL,
    avg double precision NOT NULL,
    optional real
);

