/* 
This file is auto generated by pgx.

The ordering of items is not stable, it is driven by a dependency graph.
*/

-- extension/src/lib.rs:20
-- table_builder::__table_builder_insert_InsertExample
CREATE OR REPLACE FUNCTION public."__table_builder_insert_InsertExample"() RETURNS TABLE (
	"foo" integer,  /* i32 */
	"avg" real  /* core::option::Option<f32> */
)
 STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '__table_builder_insert_InsertExample_wrapper';

-- extension/src/lib.rs:20
CREATE TABLE InsertExample (
    foo integer NOT NULL,
    avg real
);
INSERT INTO InsertExample SELECT * FROM "__table_builder_insert_InsertExample"();
DROP FUNCTION "__table_builder_insert_InsertExample";


-- extension/src/lib.rs:10
CREATE TABLE ExampleTable (
    foo integer NOT NULL,
    bar bigint NOT NULL,
    baz text NOT NULL,
    avg double precision NOT NULL,
    optional real
);

